$( function() {
  var LWLavailableTags = [
  "911",
  "Weight Management",
  "Diabetes Education and Support",
  "Medical Clinics and Groups",
  "Clothing and Supplies",
  "Financial Assistance",
  "Westgate Chapel Food & Clothing  Bank",
  "Health Care Coverage",
  "Online and Phone Resource Connections",
  "Career Transititons",
  "Internet and Phone Access - check websites for all affiliates",
  "Internet and Phone Access - Everett Youth Access",
  "Internet and Phone Access - Lynnwood",
  "Internet and Phone Access - Monroe",
  "Workforce",
  "4-H Youth Development",
  "Growing Groceries",
  "Healthy Families - SNAP Program",
  "Event Arena",
  "Youth Development Center - Marysville",
  "Recreation Centers/Activities/Gyms - Everett",
  "Recreation Centers/Activities/Gyms - Marysville",
  "Recreation Centers/Activities/Gyms - Mill Creek",
  "Recreation Centers/Activities/Gyms - Monroe",
  "Recreation Centers/Activities/Gyms - Mukilteo",
  "Recreation Centers/Activities/Gyms - Stanwood",
  "Y Casino Road Community Center",
  "Youth Healthy Living Fitness and Sports",
  "Silver Sneakers",
  "Providence Health Services, NW Region",
  "Drop In and Loss Specific Grief Support",
  "Puget Sound Christian Clinic Mobile Medical Clinic Sites",
  "Lynnwood @ Trinity Lutheran Church",
  "Snohomish @ Cross View Church",
  "Puget Sound Kidney Centers",
  "Kidney Disease Education and Support",
  "Quilceda Community Services",
  "Willow Place",
  "Rainbow Counseling and Equine Connections",
  "Counseling and Trauma Support",
  "Reflections",
  "Dance",
  "Refugee & Immigrant Services NW",
  "Refugee Forum",
  "Refugee and Immigrant Services NW",
  "Regional Access Mobility Program (RAMP)",
  "Housing Programs and Resources",
  "Resolute Fitness",
  "Personal Training, Groups and Boot Camp Classes",
  "Run 2 Be Fit",
  "Personal Training and Fitness Groups/Events",
  "Safe Harbor Free Clinic",
  "Community Clinic",
  "Safelink Wireless",
  "Internet and Phone Access",
  "Salvation Army",
  "Back to School Clothing and Supplies",
  "Housing",
  "Weekly Onsite Meals",
  "Food Bank, Food Pantry",
  "Samurai Karate Academy",
  "Karate",
  "Sauk-Suiattle Indian Tribe",
  "Health and Social Services Department, Pow Wow, Daycare and Preschool,",
  "Sea Mar Community Health Centers",
  "Health Eating and Cooking",
  "Behavioral Health - Mental Health Services Everett",
  "Behavioral Health - Mental Health Services Lynnwood",
  "Behavioral Health - Mental Health Services Monroe",
  "Marysville Medical Clinic",
  "Monroe Medical Clinic",
  "Everett Medical Center",
  "Behavioral Health - Chemical Dependency Services Everett",
  "Behavioral Health - Chemical Dependency Services Lynnwood",
  "Teen Programs",
  "Swimming Pools and Swim Lessons",
  "Yoga and Meditation",
  "Youth and Family Community Leadership",
  "Working Wardrobe",
  "Pathways to Work",
  "BABES Network - peer support program for women and families affected by HIV",
  "Shelter and Transitional Housing",
  "Legal Services",
  "Everett Regional Center",
  "Civic Advocacy",
  "Self-Defense",
  "Emergency Reporting Hotline",
  "Smart 911 Safety Profile",
  "10 Minute Walk-in Clinic",
  "Walk-In Clinic",
  "24-Hour Fitness",
  "30/10 Weight Loss for Life",
  "Weight Loss Program",
  "Affordable Counseling",
  "Mental Health Needs for children, teens, adults, couples and families",
  "Aikido Heiwa-Martial Arts for Peace",
  "Karate and Martial Arts",
  "Behavioral Health - Chemical Dependency Services Monroe",
  "Seattle Goodwill Industries",
  "Everett Location",
  "Marysville Location",
  "Program and Classes for Speakers of Other Languages",
  "Senior Center Edmonds",
  "Health and Wellness Programs",
  "Senior Services of Snohomish County",
  "Lifespan Respite Program",
  "Senior Companion Program",
  "Family Caregiver Support Program",
  "Social Services for Seniors",
  "Meals on Wheels",
  "Mental Health Services",
  "Food and Nutrition Assistance for Seniors",
  "Center for Healthy Living",
  "Living Well Workshops",
  "Relatives as Parents Program",
  "Alderwood Dance Spectrum",
  "Dance, Drama, Gymnastics",
  "All Aboard",
  "Recreational, social, and educational activities for adults with special needs",
  "Allen Creek Community Church Resource Exchange",
  "Resource Food Exchange Program",
  "American Cancer Society",
  "Road to Recovery",
  "American Diabetes Association",
  "Diabetes Camp Sealth",
  "Stop Diabetes Initiative",
  "American Red Cross of Snohomish County",
  "BLS Training for Healthcare and Public Safety",
  "Contact and Locate Loved Ones",
  "Adult and Youth Volunteer Opportunities",
  "Certified Nurse Assistant (CNA) Training",
  "CPR Training",
  "Lifeguarding",
  "First Aid",
  "Take a Class",
  "AED",
  "Northwest Region - Community Happenings & News",
  "Train My Employees",
  "Babysitting and Child Care",
  "EMT Training",
  "Disaster Preparedness Education and Training",
  "Disaster Relief",
  "Language Bank - Interpretation and Translation",
  "Swim Classes & Water Safety Training",
  "Service to the Armed Forces",
  "Anytime Fitness",
  "Health and Fitness Club",
  "Arlington Business Association",
  "Events and Services",
  "Arlington Community Food Bank",
  "Arthur Murray",
  "Senior Services Snohomish County",
  "Home Repair",
  "Sharing Wheels Community Bike Shop",
  "Community Bike Shop",
  "Silver Lake Excalibur Disc Golf Course",
  "Disc Golf Course",
  "Snap Fitness",
  "SnoCo CrossFit",
  "Strength and Conditioning Facility",
  "Snohomish Aquatic Center/Snohomish School District",
  "Swimming Pools and Spray Parks",
  "Snohomish Bicycles",
  "Bike Shop and Bike Rentals",
  "Snohomish Community Food Bank",
  "Snohomish County Music Project",
  "Artistic Citizenship",
  "Snohomish County Tourism Bureau and Visitor Information Centers",
  "Tourism and Visior Informaiton - Future of Flight",
  "Tourism and Visitor Information - East Snohomish County Branch",
  "Tourism and Visitor Information Snohomish County",
  "Visitor and Tourism South Snohomish County",
  "Snohomish Fitness Center",
  "Health Club/Gym and Classes",
  "Snohomish Health District",
  "WIC Everett",
  "WIC Lynnwood",
  "Emergency Preparedness",
  "Low Cost Dental Resources in Snohomish County",
  "First Steps",
  "Children with Special Health Care Needs",
  "Depression and Suicide Resources Listings",
  "ChildCare Provider Resources",
  "Parenting Resources",
  "Women Infants and Children WIC",
  "Food Assistance for Women, Infant and Children with limited income",
  "Snohomish Legal Services",
  "Snohomish Senior Center",
  "Senior Fitness",
  "Sno-King Counseling LLC",
  "Sno-King Counseling",
  "Social Security Administration - Snohomish County",
  "Identification and Licences",
  "Asberry Field",
  "Outdoor Fitness",
  "ATA Taekwondo Karate for Kid",
  "TaeKwon Do",
  "B.I.K.E.S. Club of Snohomish County",
  "Bike Club",
  "Barclay-Shelton Dancer Ctr",
  "Dance, Drama",
  "Bayside Bike Rentals",
  "Bethel Baptist Church",
  "Big Brothers and Big Sisters of Snohomish County",
  "Youth Support",
  "Bike and Hiking Trail Maps Snohomish County",
  "Interurban Trail Map",
  "Evergeen Mountain Bike Alliance",
  "King County Parks and Trails",
  "Puget Sound Area Trail Map",
  "Japanese Gulch Mukilteo",
  "Centennial Trail Map",
  "Communty Transit Bike Maps",
  "Brain and Body Everett",
  "Empowerment, Mind/Body",
  "Camp Fire Snohomish County",
  "Camp Willie",
  "Multigenerational Camp Fire Club",
  "Youth Club Programs & Camp Killoqua",
  "Canyon Hills Community Church Food Bank",
  "Carol Rowe Memorial Food Bank - Edmonds United Methodist Church",
  "Cascade Bicycle Club",
  "Bike Club and Bike Maps",
  "Bike Club and Bike Rentals in Seattle",
  "Cascade Senior Center",
  "Senior Support",
  "Cascade Valley Hospital and Local Clinics",
  "Hospital",
  "Cascadia Community College",
  "Public Community College",
  "Catholic Community Services of Western Washington - Snohomish County",
  "Child, Youth and Family Services",
  "Behavioral Health Center",
  "Recovery Center",
  "Baby Layette Progam",
  "Re-Entry Support",
  "Spark Hot Yoga",
  "Hot Yoga",
  "St. Vincent de Paul",
  "Broadway Bargain City Store - Clothing and Supplies",
  "Monroe - Clothing and Supplies",
  "Monsignor John G. Mattie - Clothing and Supplies",
  "Stanwood Camano Community Resource Center",
  "Stanwood Camano Food Bank",
  "Food Bank",
  "Stanwood Community and Senior Center",
  "Transportation Assistance",
  "Stillaguamish Athletic Club",
  "Stillaguamish Senior Center",
  "Sunrise Services Inc",
  "Home Care",
  "Jail Transition",
  "Swedish Hospital Edmonds",
  "Diabetes Education Center",
  "Bereavement Support",
  "Take the Next Step",
  "Tall Firs Disc Golf Course",
  "Team Child - (Legal advocacy for Youth)",
  "Team Fitness",
  "The Dance School",
  "The Everett Clinic",
  "Classes and Support Groups",
  "DBT Skills Training Group",
  "Teen Skills Group",
  "Conqering Anxiety Group",
  "Getting Better Group",
  "Living with Chronic Conditions",
  "Dementia Caregiver Support Group",
  "Refugee and Immigrant Services",
  "Refugee and Immigration Services (CRIS)",
  "Veterans Transport",
  "Volunteer Transport",
  "CDM Spiritual Center",
  "Meditation Center",
  "Center for Health and Human Services",
  "Adult and Youth Substance Abuse Prevention, Treatment, and Intervention",
  "Central Lutheran Church",
  "Parking Lot Dinners",
  "Changes Parent Support Network",
  "Peer-led Parent Support",
  "Child Protective Services Reporting",
  "Hotline",
  "Child Strive",
  "Everett Site and Administration",
  "Lynnwood Site",
  "ChildCare Aware",
  "Christmas House",
  "Citrine Health",
  "The Human Services Council (HSC)",
  "Cancer Screeining for Low Income",
  "Women's Fitness",
  "Washington Basic Food Education Program",
  "City of Arlington",
  "Twin Rivers Outdoor Fitness",
  "Twin Rivers Disc Golf Course",
  "Utility Discounts",
  "Parks and Recreation",
  "City of Bothell",
  "Explore Bothell",
  "City of Edmonds",
  "City of Edmonds/Edmonds Happenings",
  "Recreation Centers/Activities/Gyms",
  "Yost Pool",
  "Weight Loss for Life",
  "The Little Gym",
  "Gymnastics",
  "The Stillaguamish Tribe of Indians",
  "Island Crossing Counseling Center",
  "Festival of the River",
  "Therapuetic Health Services Everett/Snohomish Branch",
  "Mental Health Services - Everett",
  "Youth and Family Services - Everett",
  "Alcohol and Drug Services",
  "Tilth Alliance",
  "Farmer Markets and Community Gardens",
  "United Way of Snohomish County",
  "Volunteer Opportunities Snohomish County",
  "USTA Martial Arts",
  "Martial Arts",
  "Martial Arts - Arlington",
  "Martial Arts - Marysville",
  "Martial Arts - North Marysville",
  "Martial Arts - Smokey Point",
  "USTA Martial Arts Stanwood",
  "Martial Arts - Stanwood",
  "Verdant Health Commission",
  "Health and Wellness Classes and Support",
  "Victim Support Services",
  "Crime Victims Support and Advocacy",
  "Village Community Services",
  "Voices of the Village",
  "Vision Quest Bookstore and Wellness Center",
  "Bookstore and Wellness Center",
  "Volunteers of America Western Washington",
  "24 Hours Care Crisis Hotline",
  "Child and Youth Services (ECEAP)",
  "Food Bank, Food Pantry North Everett",
  "Food Bank, Food Pantry Mill Creek",
  "Food Bank, Food Pantry South Everett",
  "Food Bank, Food Pantry Sultan",
  "ImHurting Crisis Chat",
  "Volunteer Opportunities",
  "Legal Services - Spanish",
  "211 -Non Emergency..",
  "City of Everett",
  "Forest Park Swim Center and Outdoor Water Playground/ City of Everett",
  "Neighborhood Connections",
  "Emergency Management",
  "Carl Gipson Senior Center of Everett",
  "City of Granite Falls",
  "Granite Falls City Center",
  "City of Lake Stevens",
  "Lake Stevens City Center",
  "City of Lynnwood",
  "Senior Center, Senior Fitnes",
  "Daleway Spray Park",
  "North Lynnwood Park Spray Park",
  "Recreation Center and Swimming Pool",
  "City of Marysville",
  "Marysville/Tulalip Chamber",
  "Comeford Park Spray Park",
  "Strawberry Fields Athletic Centers",
  "Strawberry Fields Flying Disc Gold Course",
  "Ken Baxter Community Center-Senior Fitness",
  "City of Mill Creek",
  "Town Center Website (Retail)",
  "City of Monroe",
  "The Adventure Starts Here",
  "City of Mountlake Terrace",
  "Utility Services",
  "Pool and Recreation Pavillion",
  "Town Center",
  "Access to Mental Health Services",
  "Homeless Services",
  "Homeless Services, Coordinated Entry Intake Line",
  "Behavioral Health Services 24 Hour Crisis Line",
  "Developmental Disability Support Services",
  "Warm Beach Camp and Conference Center",
  "WASHED",
  "Mobile Laundry for the homeless",
  "Washington State Department of Licensing Snohomish County Offices",
  "Identification and Licenses",
  "Washington State Department of Social & Health Services Alderwood",
  "Home and Community Services Office - Alderwood",
  "Washington State Department of Social & Health Services Everett",
  "Home and Community Services Office - Everett",
  "City of Mukilteo",
  "Utility Assistance",
  "Explore Mukilteo",
  "Rosehill Community Center - Recreation Centers/Activities",
  "City of Snohomish",
  "Ferguson Parkand Disc Golf Course",
  "Historic Downtown Snohomish",
  "City of Stanwood",
  "CrabCracker Newsletter",
  "Chamber of Commerce",
  "City of Sultan",
  "News and Events",
  "ClearPoint Financial Solutions",
  "Credit Counseling",
  "Clothes for Kids",
  "Clothing and Supplies for Kids",
  "Cocoon House",
  "Youth Outreach",
  "WayOut",
  "WayOut and Project Safe",
  "Columbia Athletic Club",
  "Community Health Center of Snohomish County",
  "Community Transit - Snohomish County",
  "Dial a Ride DART",
  "Bus Transportation",
  "Compass Health - Snohomish County",
  "Counseling and Trauma Support Federal",
  "Counseling and Trauma Support Monroe",
  "Counseling and Trauma Support Smokey Point",
  "Counseling and Trauma Support Dawson Place",
  "Counseling and Trauma Support Broadway",
  "Counseling and Trauma Support Snohomish",
  "Counseling and Trauma Support Mukilteo",
  "Counseling and Trauma Support 10th Street",
  "Counseling and Trauma Support Marine View Dr.",
  "Depression and Suicide Resources",
  "Professional Workshops",
  "Counseling and Trauma Support Edmonds",
  "Re-Entry",
  "Composite CrossFit",
  "Cougar Creek Elementary",
  "Counseling Centers of North Puget Sound",
  "Family and individual classes, workshops, counseling.",
  "CrossFit Everett",
  "CrossFit Lombard",
  "CrossFit North Sound",
  "CrossFit Snohomish",
  "Dance Elite",
  "Darrington Food Pantry Bank",
  "Depression and Bipolar Support Alliance Snohomish County Chapter",
  "Domestic Violence Services of Snohomish County",
  "Shelter & Transitional Housing",
  "Domestic Violence Support",
  "Eagle’s Wing disAbility Ministries",
  "Mobile Dental Clinic, Eagle Card, Project Hello",
  "East County Senior Center",
  "Edmonds Community College",
  "Workforce Development",
  "Basic ESL",
  "Marysville Cooperative Preschool",
  "Mill Creek Cooperative Preschool",
  "West Edmonds Cooperative Preschool",
  "Central Washington University Partnerships",
  "Online Bachelor's Degree University of Washington",
  "Edmonds Cooperative Preschool",
  "Center for Families Cooperative Preschool",
  "Playful Learning Cooperative Preschool",
  "Snohomish Cooperative Preschool",
  "Diversity Student Center",
  "Equity and Diversity Center",
  "Intensive ESL",
  "Lake Stevens Cooperative Preschool",
  "Online Bachelor's Degree Washington State University",
  "Edmonds Lutheran Church",
  "Annie's Community Kitchen",
  "Edmonds Senior Center",
  "Exercise Classes",
  "Edmonds United Methodist Church",
  "Emerald City Athletics",
  "Esculent Health",
  "Nutritional Theraphy",
  "Everest College",
  "Private for-profit",
  "Everett Community College",
  "Bridges Center",
  "Diversity and Equity Center",
  "Employer Resources",
  "Workforce Training and Development",
  "Multicultural Student Success Center and Women's Program",
  "Volunteer Literacy Program",
  "English Language Acquisition ELA/ESL",
  "Early Learning Center",
  "Everett Community Justice Center",
  "Everett Gospel Mission",
  "Men's Shelter & Donation Center",
  "Feed Hope Kitchen",
  "Essential Needs Program",
  "Clothing and Supplies Men, Women and Children",
  "Women and Children's Shelter",
  "Administration and Overview",
  "Men's Shelter",
  "Everett High School",
  "Everett Housing Authority",
  "Housing Authority & Coordinated Entry",
  "Community Housing Improvement Program (CHIP)",
  "Everett Public Library",
  "Everett Recovery Café",
  "Drop-In Centers",
  "Everett Silvertips",
  "Hocky",
  "Everett Skate Deck",
  "Everett United Church of Christ",
  "Food Bank and Weekly Community Meal",
  "Everett University Center",
  "University of Washington Bothell",
  "The Evergreen State College",
  "Central Washington University",
  "Eastern Washington University",
  "Hope International University",
  "University Center",
  "Western Washington University",
  "Washington State University",
  "Evergreen Food and Goods Rescue",
  "Evergreen Recovery Centers",
  "Detoxification Unit",
  "Residential Daycare and Addiction Treatmet for Women",
  "Adminstration Offices",
  "Outpatient Everett",
  "Outpatient Lynnwood",
  "EvergreenHealth Monroe",
  "Eviva",
  "Medical weight loss program and bariatric procedures",
  "Explorer Middle School",
  "Faith Lutheran Church",
  "Food Pantry for persons in need",
  "Family Karate Center",
  "Family Karate Ronin Dojo",
  "Father's House Community Food Bank",
  "First Class Ballroom",
  "Ball Room Dance",
  "First Presbyterian Church of Everett",
  "Fitness Evolution",
  "Friends of Youth (youth and parenting youth)",
  "Headquarters",
  "New Ground Transitional Living Program",
  "Gay City",
  "Girls on the Run of Snohomish County",
  "Girls on the Run",
  "Girls on the Run Snohomish County",
  "GLOBE",
  "Gay Lesbian Bi-Sexual Youth Empowerment Support Group",
  "Gay, Lesbian, or Bi-Sexual Empowerment  - for youth",
  "Gold's Gym",
  "Granite Falls Food Bank",
  "Granite Falls Senior Center",
  "Hand in Hand/Safe Place",
  "Clothing and Supplies for the Community",
  "Health Point Bothell Clinic",
  "Historic Everett Theatre",
  "Theatre",
  "Hot Yoga of Mill Creek",
  "Housing Hope",
  "Housing Hope Day Care",
  "Shelter & Transitional",
  "Ideal Weight Loss Clinic of Everett",
  "Ideal Protein Diet Protocol",
  "Ideal Wellness",
  "Imagine Children’s Museum",
  "Interfaith Association of Northwest Washington",
  "Interfaith Association",
  "Jenny Craig Weight Loss Center",
  "Weight Loss Support",
  "Job Corps",
  "Youth Resources",
  "KADAMPA Meditation Center Washington",
  "Snohomish County Classes",
  "Kids Stage",
  "Drama, Dance",
  "Kontagious Dance",
  "Kung Fu Northwest",
  "LA Fitness",
  "Lake Stevens Community Food Bank",
  "Lake Stevens Disc Golf Course",
  "Lake Stevens High School",
  "Lake Stevens Senior Center",
  "Lakewood High School",
  "Latino Education Training Institute",
  "Mexican Folklore and Regional Dance",
  "Leading Edge Gymnastics Academy",
  "League of Women Voters",
  "Legal Voice",
  "Lifelong/Evergreen Wellness Advocates",
  "HIV Counseling, Testing and Chronic Disease Management",
  "HIV/AIDS Support, Care Management and HIV Testing",
  "Lutheran Community Services NW",
  "Drop-In Center",
  "Community Resource Center - Familias Unidas",
  "For Kids' Sake Parenting Seminar",
  "Community Resource Center - Arlington",
  "Family Support Center - South Snohomish County",
  "Community Resource Center - Granite Falls",
  "Community Resource Center - Lake Stevens",
  "South Everett Neighborhood Center",
  "Emergency Food Pantry",
  "Lutheran Community Sevices NW",
  "Arlington Community Chest",
  "Lutheran Counseling Network",
  "Lynnwood Food Bank",
  "Maltby Food Bank",
  "Marysville Community Food Bank",
  "Marysville Performing Art Center",
  "Master Builders Care Foundation",
  "Medical Reserve Corps",
  "Emergency Mangement",
  "Mercy Housing and Housing Consortium of Everett and Snohomish County",
  "Mill Creek Family Services",
  "Mill Creek Senior Center",
  "Millionair Club - Seattle",
  "Molina Healthcare of Washington, Inc.",
  "Monroe (Sky Valley) Food Bank",
  "Monroe Gospel Women's Mission",
  "Monroe High School Stadium",
  "Morning Star Korean Cultural",
  "Koren Dance, Music, Heritage",
  "Mountlake Terrace Community Senior Center",
  "Mountlake Terrace Food Bank - Concern for Neighbors",
  "Mukilteo Food Bank",
  "NAMI - National Alliance on Mental Illness Snohomish County",
  "Mental health support groups, education and advocay",
  "Navy Marine Corp Relief Society - Snohomish County",
  "Veterans Assistance",
  "New Life Prison Ministry",
  "North Sound Mental Health Administration",
  "Improving the mental health and well being of individuals and families",
  "Northshore Senior Center",
  "Northshore Youth and Family Services",
  "Substance abuse treatment and Mental Health - Dual Diagnosis",
  "Northwest Dance and Acro Center",
  "Dance and Acro",
  "Northwest Justice Project - Snohomish County",
  "Northwest Weight Loss Surgery",
  "Weight Loss Surgery",
  "Olympic Ballet",
  "Ballet School",
  "Our Common Ground Church",
  "Our Common Table Potluck Meal",
  "Hospitality Space - Drop-In Center",
  "Outdoors For All Foundation",
  "Outdoors for All's programs",
  "Pacific Chamber Ballet",
  "Ballet Training",
  "Pacific Karate Organization",
  "Pacific West Performing Arts",
  "PAVE",
  "Disability Resources",
  "Peak Health and Fitness",
  "Health Club/Gym",
  "Phoenix Games in Mukilteo",
  "Poison Control",
  "Poisoning Emergencies and Questions",
  "Pregnancy Aid of Snohomish County",
  "Maternity and Baby Clothing and Supplies",
  "Pregnancy Resource Center",
  "Pregnancy Resources and Health Care",
  "Program for Early Parent Support",
  "Parent Support and Family Activities",
  "The cancer Resource center",
  "Standing Together. Individual and group support",
  "Cancer Support Groups",
  "Youth and Children's Fitness",
  "After Your Baby Is Born Classes",
  "You Are Not Alone",
  "Everett Office - Corporate Office Snohomish County and Administration",
  "Individual, Group, and Family Counseling Services",
  "AWAKE Support Group - Sleep Health Institute",
  "Critical Incident Stress Management and Spirtual",
  "Therapeutic Care for Children & Teens",
  "Feeding Group",
  "A Tour of Health Care & The Human Body",
  "Kids Have Many Kinds of Losses youth support group",
  "Prostate Cancer Support Group",
  "Pulmonary Rehab",
  "Cardiac Rehab",
  "Camp Erin Youth Support Group",
  "Providence Regional Cancer Parntership",
  "Joint Classes and Seminars",
  "Behavioral Health - Drug and Alcohol Addiction Treatment & Detox",
  "Nutrition",
  "Support Group for Cancer Patients and Survivors",
  "Providence Hospice and Home Care of Snohomish County",
  "Gentle Yoga",
  "Gentle yoga",
  "Food, Fun & Conversations",
  "Grief Supporf for Adults - individual and group support",
  "Teens & Children individual and group support",
  "Women with Cancer Support Group",
  "Look good. Feel better",
  "Stop Smoking Tool Shop",
  "Volunteer Services",
  "Art therapy",
  "Survivorship Series",
  "Providence Intervention Center for Assualt and Abuse"
];




  var LHavailableTags = [
  "City of Mukilteo",
  "Japanese Gulch Park Stewardship",
  "Food Lifeline",
  "Food Lifeline - Snohomish County Agency Food Banks",
  "Northwest Ambulance Critical Care Transport",
  "Employee Health",
  "Cocoon House",
  "Cocoon House - Improving Nutrition/Increasing Physical Activity",
  "Jennifer Smolen",
  "Jennifer Smolen - Improving Nutrition/Increasing Physical Activity",
  "Wendie Collins",
  "Wendie Collins - Improving Nutrition/Increasing Physical Activity",
  "Lindsey Wilson",
  "Lindsey Wilson - Improving Nutrition/Increasing Physical Activity",
  "Shelly Henderson",
  "Shelly Henderson - Improving Nutrition/Increasing Physical Activity",
  "Softcare Dental",
  "Softcare Dental - Improving Nutrition/Increasing Physical Activity",
  "Snohomish County ECEAP",
  "Snohomish County ECEAP - Improving Nutrition/Increasing Physical Activity",
  "Denise Crie",
  "Denise Crie - Improving Nutrition/Increasing Physical Activity",
  "Wendy Roullier",
  "Wendy Roullier - Improving Nutrition/Increasing Physical Activity",
  "Melody Young",
  "Melody Young - Improving Nutrition/Increasing Physical Activity",
  "Shannon Kessler",
  "Shannon Kessler - Improving Nutrition/Increasing Physical Activity",
  "City of Mukilteo - Improving Nutrition/Increasing Physical Activity",
  "Edward Sharpless",
  "Edward Sharpless - Improving Nutrition/Increasing Physical Activity",
  "Snohomish County Assessor",
  "Snohomish County Assessor - Improving Nutrition/Increasing Physical Activity",
  "Citrine Health",
  "Citrine Health - Improving Nutrition/Increasing Physical Activity",
  "Integrated Rehabilitation Group",
  "Integrated Rehabilitation Group - Increasing Physical Activity",
  "Hope Family Medical Clinic, PLLC",
  "Hope Family Medical Clinic, PLLC - Improving Nutrition/Increasing Physical Activ",
  "Housing Hope",
  "College of Hope - Health and Wellness",
  "Hoff Foundation",
  "Esther's Place",
  "Lutheran Community Services NW",
  "Healthy Families",
  "Project Access Northwest",
  "Workforce wellness program",
  "Neighbors in Need",
  "Neighbors in Need - Improving Nutrition",
  "Everett School District",
  "Everett Public Schools - Improving Nutrition/Increasing Physical Activity",
  "Everett Community College",
  "Everett Community College - Increasing Physical Activity",
  "Compass Health",
  "Refugee & Immigrant Services NW",
  "Refugee & Immigrant Services NW - Improving Nutrition/Increasing Physical Activi",
  "Providence Northwest Region",
  "Workplace Activity Challenge",
  "Beanfields Snacks",
  "Beanfields Snacks - Improving Nutrition",
  "Bethany Christian Assembly",
  "Bethany Christian Assembly - Improving Nutrition/Increasing Physical Activity",
  "Arbonne",
  "Arbonne - Improving Nutrition",
  "Arlington School District",
  "Arlington Public Schools - Improving Nutrition/Increasing Physical Activity",
  "Camp Fire Snohomish County",
  "Camp Fire Snohomish County - Improving Nutrition/Increasing Physical Activity",
  "Community Resources Foundation",
  "Community Resources Foundation - Improving Nutrition/Increasing Physical Activit",
  "City of Lynnwood",
  "City of Lynnwood - Healthy Communities Action Plan",
  "Corporate Health Alliance",
  "Corporate Health Alliance - Improving Nutrition/Increasing Physical Activity",
  "American Heart Association",
  "American Heart Association - Improving Nutrition",
  "Campbell's Fresh",
  "Mariner HS Career Ambassadors",
  "Providence Institute for a Healthier Community",
  "Walking for Compassion",
  "Sqord",
  "Gear Up & Go!",
  "Alzheimer's Association Washington State Chapter",
  "Community Outreach and Education",
  "Connections Care Consultation",
  "Support Groups",
  "Early Stage Memory Loss Programs (ESML)",
  "Everett Farmers Market LLC",
  "Everett Farmers Market LLC - Improving Nutrition",
  "Match the Snap Incentive",
  "Happy Hoppers Inc",
  "Happy Hoppers Inc - Increasing Physical Activity",
  "Marysville School District",
  "Marysville School District - Increasing Physical Activity",
  "Pamela LaVergne",
  "Pamela LaVergne - Increasing Physical Activity",
  "Snohomish Running Company",
  "Kla Ha Ya Beats 5k/10k",
  "Summer Beats Half Marathon and 10k",
  "Snohomish River Run",
  "Mukilteo Turkey Trot",
  "Edmonds Senior Center",
  "Bastyr Center for Natural Health Medicine Clinic",
  "Enhance Wellness Program",
  "PEARLS",
  "Enhance Fitness",
  "Soft Fitness",
  "Everett Community Streets Initiative",
  "Oral Cancer / Smiles for Veterans",
  "Oral Cancer Foundation",
  "GoNoodle Sponsorship",
  "Puget Sound Kidney Centers",
  "Healthy Options",
  "Survive and Thrive",
  "Smiles for Veterans",
  "Hero House/NAMI",
  "Mindfulness Teaching",
  "Leadership Snohomish County",
  "Healthcare and Human Services Day",
  "Leadership Snohomish County Signature Class",
  "Institute of Flight",
  "Healthy meeting and retreat site",
  "Sea Mar Community Health Center",
  "Community Kitchen",
  "24/7 HELPLINE 1-800-272-3900",
  "American Diabetes Association",
  "Diabetes Inside",
  "Wellness Lives Here",
  "Community Foundation of Snohomish County",
  "Coordination, training and funding",
  "Casino Road Collective Impact",
  "Campbell's StockPot - Improving Nutrition/Increasing Physical Activity",
  "Klesick Family Farm",
  "Neighbor Helping Neighbors",
  "Backbone Support - LiveHealthy2020",
  "Boys & Girls Clubs of Snohomish County",
  "TriplePlay",
  "Domestic Violence Services of Snohomish County",
  "Healthy Living for clients and staff",
  "liberty garden",
  "Everett Transit",
  "Active Transportation Support",
  "Heath living",
  "Seattle CityClub",
  "Seattle CityClub - Increasing Physical Activity",
  "Snohomish County Food Bank Coalition",
  "D.A. Davidson",
  "D.A. Davidson -Lunch Time walking program",
  "Snohomish County PUD",
  "xx",
  "Port of Everett",
  "Waterfront Place",
  "Mukilteo School District",
  "Gear Up and Go - Increasing Physical Activity",
  "WSU Snohomish County Extension",
  "SNAP-Ed",
  "Youth Soccer Club",
  "Running Club",
  "Punch Card for Fitness",
  "Mercy Housing Northwest",
  "Mercy Housing Northwest - Improving Nutrition/Increasing Physical Activity",
  "Volunteers of America Western Washington",
  "Everett Food Bank",
  "Behavioral Health Services",
  "Edmonds Community College Foundation",
  "Edmonds Community College Foundation - Improving Nutrition/Increasing Physical A",
  "Workplace Health Solutions",
  "Food & Beverage Guide",
  "Get Moving!",
  "Private Program",
  "School Meal Program",
  "Summer Meal Program",
  "The Boeing Company",
  "Boeing on the Move",
  "Economic Alliance Snohomish County",
  "Economic Alliance Snohomish County - Improving Nutrition/Increasing Physical Act",
  "Sound Media",
  "Marcomm Support",
  "American Cancer Society",
  "Active For Life",
  "Aquatic Physical Therapy",
  "Balance & Fall Prevention",
  "Bike Fitting",
  "Massage Therapy",
  "Granite Falls Community Coalition",
  "Community Health Center of  Snohomish County",
  "Kids Cafe - Summer Meals",
  "Nutrition Counseling",
  "Vestibular Rehabilitation",
  "Pilates Sessions",
  "Pediatric Therapy",
  "Women's Health",
  "Improving Nutrition Providence NWR",
  "Men's Health",
  "Tulalip Tribes",
  "Tulalip Cares",
  "Community Transit",
  "Community Transit - Increasing Physical Activity",
  "Making Activity Possible Again",
  "Farmer Frog",
  "Farmer Frog School Gardens & Non-school Farms",
  "Employee Wellness Program",
  "Lymphedema Treatment",
  "Coastal Community Bank",
  "Coastal Community Bank - Improving Nutrition/Increasing Physical Activity",
  "Diamond Veterinary Associates",
  "Diamond Veterinary Associates - Improving Nutrition/Increasing Physical Activity",
  "Edmonds Senior Center - Improving Nutrition/Increasing Physical Activity",
  "Food Lifeline - Kids Cafe",
  "Girl Scouts of Western Washington",
  "Girl Scouts of Western Washington - Improving Nutrition/Increasing Physical Acti",
  "Edmonds Community College",
  "Live Well/Employee Wellness",
  "I-CATCH Allied Health HPOG Grant",
  "EdCC Wellness Center",
  "Center for Inclusive Entrepreneurship",
  "CommunityEnterprise",
  "Premera Blue Cross",
  "Premera Blue Cross - Premera Employee Wellness Program",
  "Tomorrow's Hope Child Development Center",
  "Homeless Family Services",
  "Sultan School District",
  "Water Bottle Filling Station",
  "Hope Works",
  "CafeWorks",
  "Mari's Place",
  "Mari's Place Art Classes",
  "Industrial Massage",
  "Pain Intervention",
  "Just Real Stuff Wellness",
  "Whole Foods Cooking, Elimination Diet, and Holistic Health Programs",
  "MUGS/ \"Mukilteo User Group\" - Salesforce/Community Partner Portal",
  "Health Hacks & Yummy Snacks",
  "Experience Momentum",
  "Unlimited Fitness Membership",
  "Synergy HomeCare of Snohomish County",
  "Nutritious Eating Program",
  "Hand in Hand",
  "Village Impact Project",
  "Snohomish County Sports Commission",
  "Youth Sports Festival",
  "Good Food Treasure Box",
  "SOIL to STEM",
  "Peas 4 Peace",
  "Farmers Market",
  "School backpacks",
  "Archbishop Murphy High School",
  "Faculty Wellness",
  "Saturday Sports Injury Clinic",
  "Taylor Gregory Broadway Architects",
  "Keep Us Movin'",
  "Healthy Activity Program",
  "Town of Woodway",
  "Rachael Chiarelli",
  "Initial Consultation",
  "DiNovi Performance",
  "Breakthrough with Brandon DiNovi",
  "Artemis Connection, Inc.",
  "Human sustainable workplaces",
  "Outdoor Youth Connections",
  "SHAG - Senior Housing Assistance Group",
  "Group Exercise Classes",
  "Kor Fitness",
  "Small Group Personal Training",
  "Foundation for Edmonds School District",
  "Nourishing Network - weekend meals",
  "Nourishing Network - holiday meals",
  "Nourishing Network - hygiene kits",
  "Project Harvest",
  "The Vitamin Shoppe / Super Supplements",
  "Inspire,Nourish,Thrive Everyday",
  "Faith Community Nursing in Snohomish County",
  "Prayer Shawls",
  "Cold Weather Shelter",
  "Dental Clinic and Screenings",
  "Mobile Medical Van",
  "Walking Program",
  "Gardens for Children",
  "Donated Cropland",
  "Arlington Senior Resource Center",
  "Sound Dietitians",
  "Community Nutrition Education",
  "Snohomish Region Farmers Market Coalition",
  "Everett Farmers Market",
  "United Healthcare",
  "Small Steps",
  "Marysville Farmers Market",
  "Edmonds Family Medicine",
  "Your Life Your Wishes",
  "Pointe of Grace Teaching Garden",
  "Blythe Associates",
  "Test Program",
  "Center for Community Health & Evaluation (Group Health Research Institute)",
  "LH2020 evaluation",
  "Adjusting Your Climate Thermostat",
  "Everett Housing Authority",
  "Nutritional Education"
];
  $( "#LWLautocomplete" ).autocomplete({
    source: LWLavailableTags
  });
  $( "#LHautocomplete" ).autocomplete({
    source: LHavailableTags
  });

} );
